import { pgEnum, pgTable, uuid, varchar, text, timestamp, boolean, integer, uniqueIndex, index } from "drizzle-orm/pg-core";

export const electionStatus=pgEnum("election_status",["draft","scheduled","open","closed","published"]);
export const userRole=pgEnum("user_role",["owner","admin","auditor"]);
export const organizations=pgTable("organizations",{id:uuid("id").primaryKey().defaultRandom(),name:varchar("name",{length:180}).notNull(),slug:varchar("slug",{length:80}).notNull().unique(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()});
export const users=pgTable("users",{id:uuid("id").primaryKey().defaultRandom(),organizationId:uuid("organization_id").references(()=>organizations.id,{onDelete:"cascade"}).notNull(),name:varchar("name",{length:140}).notNull(),email:varchar("email",{length:255}).notNull(),passwordHash:text("password_hash").notNull(),role:userRole("role").default("admin").notNull(),disabled:boolean("disabled").default(false).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex("users_org_email_uq").on(t.organizationId,t.email)]);
export const elections=pgTable("elections",{id:uuid("id").primaryKey().defaultRandom(),organizationId:uuid("organization_id").references(()=>organizations.id,{onDelete:"cascade"}).notNull(),name:varchar("name",{length:220}).notNull(),description:text("description"),opensAt:timestamp("opens_at",{withTimezone:true}).notNull(),closesAt:timestamp("closes_at",{withTimezone:true}).notNull(),status:electionStatus("status").default("draft").notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>[index("elections_org_idx").on(t.organizationId)]);
export const positions=pgTable("positions",{id:uuid("id").primaryKey().defaultRandom(),electionId:uuid("election_id").references(()=>elections.id,{onDelete:"cascade"}).notNull(),name:varchar("name",{length:120}).notNull(),description:text("description"),maxSelections:integer("max_selections").default(1).notNull(),sortOrder:integer("sort_order").default(0).notNull()});
export const candidates=pgTable("candidates",{id:uuid("id").primaryKey().defaultRandom(),positionId:uuid("position_id").references(()=>positions.id,{onDelete:"cascade"}).notNull(),name:varchar("name",{length:140}).notNull(),department:varchar("department",{length:140}),statement:text("statement"),photoUrl:text("photo_url"),symbol:varchar("symbol",{length:12}),sortOrder:integer("sort_order").default(0).notNull(),active:boolean("active").default(true).notNull()});
export const voters=pgTable("voters",{id:uuid("id").primaryKey().defaultRandom(),organizationId:uuid("organization_id").references(()=>organizations.id,{onDelete:"cascade"}).notNull(),voterCode:varchar("voter_code",{length:80}).notNull(),name:varchar("name",{length:140}).notNull(),email:varchar("email",{length:255}),phone:varchar("phone",{length:40}),department:varchar("department",{length:140}),year:varchar("year",{length:40}),campus:varchar("campus",{length:120}),passwordHash:text("password_hash").notNull(),disabled:boolean("disabled").default(false).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>[uniqueIndex("voters_org_code_uq").on(t.organizationId,t.voterCode),index("voters_org_idx").on(t.organizationId)]);
export const eligibility=pgTable("voter_election_eligibility",{id:uuid("id").primaryKey().defaultRandom(),voterId:uuid("voter_id").references(()=>voters.id,{onDelete:"cascade"}).notNull(),electionId:uuid("election_id").references(()=>elections.id,{onDelete:"cascade"}).notNull(),eligible:boolean("eligible").default(true).notNull(),votedAt:timestamp("voted_at",{withTimezone:true})},t=>[uniqueIndex("eligibility_voter_election_uq").on(t.voterId,t.electionId),index("eligibility_election_idx").on(t.electionId)]);
// No voter identifier is present in this table or its selections.
export const ballots=pgTable("ballots",{id:uuid("id").primaryKey().defaultRandom(),electionId:uuid("election_id").references(()=>elections.id,{onDelete:"restrict"}).notNull(),receiptHash:varchar("receipt_hash",{length:64}).notNull().unique(),castAt:timestamp("cast_at",{withTimezone:true}).defaultNow().notNull()},t=>[index("ballots_election_idx").on(t.electionId)]);
export const ballotSelections=pgTable("ballot_selections",{id:uuid("id").primaryKey().defaultRandom(),ballotId:uuid("ballot_id").references(()=>ballots.id,{onDelete:"restrict"}).notNull(),positionId:uuid("position_id").references(()=>positions.id,{onDelete:"restrict"}).notNull(),candidateId:uuid("candidate_id").references(()=>candidates.id,{onDelete:"restrict"}).notNull()},t=>[uniqueIndex("ballot_position_uq").on(t.ballotId,t.positionId)]);
export const auditLogs=pgTable("audit_logs",{id:uuid("id").primaryKey().defaultRandom(),organizationId:uuid("organization_id").references(()=>organizations.id,{onDelete:"restrict"}).notNull(),actorId:uuid("actor_id"),action:varchar("action",{length:120}).notNull(),entityType:varchar("entity_type",{length:80}).notNull(),entityId:uuid("entity_id"),metadata:text("metadata"),ipHash:varchar("ip_hash",{length:64}),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()},t=>[index("audit_org_created_idx").on(t.organizationId,t.createdAt)]);
